# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d00cceccf1b0f8af3bb8c65c825045213693a22f2856da9e2933f7e588ff643c0989e828d9b6b7054686ffeac7e897ce9b870ea52aa90abe35cb4072792e31d1

test:
  secret_key_base: 75c166853a7288c100e9d83348f725cebeee5c4c9611ab18dde13a0ab6c90b4c8b177f72b835a0f3faf053480bb17a58f44c30f1ba56fc8024f25125e532ddf0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
